### ISSUE TITLE
My trial at installing this...

### ISSUE THREAD

**Issue by UnixJunkie** [insilichem/tangram_plipgui#2]
```
sudo apt install python2.7-openbabel
pip install plip
pip install https://github.com/insilichem/libtangram/archive/v0.0.2.zip
pip install https://github.com/insilichem/tangram_plipgui/archive/v0.0.2.zip
```

Then, when I launch chimera:
```
Error while importing plipgui from /home/berenger/.local/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/home/berenger/usr/chimera-1.13/share/chimera/extension/base.py", line 351, in _importExtension
    __import__(module)
  File "/home/berenger/.local/lib/python2.7/site-packages/plipgui/ChimeraExtension.py", line 8, in <module>
    from plipgui.core import cmd_plip, cmd_unplip
  File "/home/berenger/.local/lib/python2.7/site-packages/plipgui/core.py", line 50, in <module>
    from plip.modules.preparation import PDBComplex
  File "/home/berenger/.local/lib/python2.7/site-packages/plip/modules/preparation.py", line 13, in <module>
    from .detection import *
  File "/home/berenger/.local/lib/python2.7/site-packages/plip/modules/detection.py", line 12, in <module>
    from .supplemental import *
  File "/home/berenger/.local/lib/python2.7/site-packages/plip/modules/supplemental.py", line 27, in <module>
    from pybel import *
TypeError: Item in ``from list'' must be str, not unicode
```

If, out of despair, I try to install
```
pip install https://github.com/insilichem/libtangram/archive/v0.0.3.zip
pip install https://github.com/insilichem/tangram_plipgui/archive/v0.0.3.zip
```

Then the chimera error upon startup become:
```Error while importing plipgui from /home/berenger/.local/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/home/berenger/usr/chimera-1.13/share/chimera/extension/base.py", line 351, in _importExtension
    __import__(module)
  File "/home/berenger/.local/lib/python2.7/site-packages/plipgui/ChimeraExtension.py", line 8, in <module>
    from plipgui.core import cmd_plip, cmd_unplip
  File "/home/berenger/.local/lib/python2.7/site-packages/plipgui/core.py", line 50, in <module>
    from plip.modules.preparation import PDBComplex
ImportError: No module named plip.modules.preparation
```

So, in both cases, I don't get the tangram-plip GUI installed into my chimera...
:(

**Comment by UnixJunkie** [comment]
By the way, what is the recommended install method?
I.e. the one that is the most reproducible, working out of the box, fully automatic.

Alternatively, could you provide a virtual machine where this thing is installed and correctly working?

**Comment by UnixJunkie** [comment]
By the way, I am not using conda.
If I should, please tell me.
Also, all the commands to install things on a freshly installed Ubuntu would be nice (because using conda means we need to install more things via conda, I suppose).

**Comment by jaimergp** [comment]
Hi! Due to incompatibilities between `openbabel`, `rdkit` and `pychimera` we had to take `plipgui` from the main Tangram distribution. Currently there is no straightforward way to install it, so we have to go the manual way...

I will have to test this, but if you want to try:

- `plip`, `tangram_plipgui` and `libtangram` must be installed into `$CHIMERA/share` or `$CHIMERA/lib/python2.7/site-packages`. 
- `openbabel` must be installed in your system and somehow discoverable by Chimera. I can't remember how to do this now, but there should be a way (last resource, installing it in the Chimera distribution).

Alternatively, using `pychimera`  and `conda` you should be able to create a `conda` environment with the needed packages that can be "injected" into a slightly patched UCSF Chimera installation (Numpy upgraded). As you see, not the smoothest process. We can try to prepare a VM image, full installation script for a clean Ubuntu 18.04 or a docker image... but I cannot provide a deadline now. We can also arrange a one-on-one call if you want me to live debug the installation process.

There are ways around this, but none of them is easy/simple/quick. Solution (A) would involve forking `plip` so it doesn't rely on openbabel, but directly on `chimera`. Solution (B) would be migrating the UI to ChimeraX for a more modern Python environment.

Best,
Jaime.

**Comment by UnixJunkie** [comment]
OK, don't bother.
I found the plip webserver online.
Enough for my need.
Thanks for the help though.
In the future, for end users, it would be nice if a 'pip3 install plipgui' or something similar would work,
install all required dependencies automatically, etc.
